# Just for reference
# https://github.com/helix-editor/helix/blob/master/languages.toml


# https://www.kernel.org/doc/html/v4.10/process/coding-style.html 
# if you need more than 3 levels of indentation, you’re screwed anyway, and should fix your program. 

[[language]]
name = "make"
scope = "source.make"
file-types = ["Makefile", "makefile", "make", "mk", "GNUmakefile"]
injection-regex = "(make|makefile|Makefile|mk|GNUmakefile)"
roots = []
comment-token = "#"
indent = { tab-width = 4, unit = "\t" }
